name: Fetch Papers & Email Results

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install arxiv \
                     requests \
                     pymupdf \
                     google-auth \
                     google-auth-oauthlib \
                     google-auth-httplib2 \
                     google-auth \
                     googleapiclient

      - name: Run script (Fetch & Summarize) and save output
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python fetch_papers.py > output.txt

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Research Papers Report"
          body: |
            Attached is today's research papers summary in text and PDF format.
            Google Doc Link: https://docs.google.com/document/d/14p892Xm1xvLIH2c1awYAYfT2_yWMYWUiKPRSo8XOcqA/edit
          to: "mhatami@sc.edu"
          from: "GitHub Actions <your-email@gmail.com>"
          attachments: |
            output.txt
            research_summary.pdf