name: Fetch Papers, Summarize with Gemini & Email Results

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_summarize_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install arxiv requests pymupdf google-auth google-auth-oauthlib google-auth-httplib2 google-auth-json

      - name: Run script and save output
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python fetch_papers.py > output.txt

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Research Papers Summary"
          body: "Attached is today's research paper summaries generated using Gemini AI."
          to: "mhatami@sc.edu"
          from: "GitHub Actions <your-email@gmail.com>"
          attachments: output.txt
